version: '3.8'

services:
  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - "8081:80"  # Antes: "80:80" pero esto me daba error
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - wordpress_data:/var/www/html  
    depends_on:
      - mysql
    restart: always
    networks:
      - frontend-network
      - backend-network

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin:5.1
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always
    networks:
      - frontend-network
      - backend-network

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: "${DOMAIN} -> http://wordpress:80"
      STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    networks:
      - frontend-network

volumes:
  wordpress_data:
  mysql_data:

networks:
  frontend-network:
  backend-network: